services:
  - type: web
    name: astra-session-breakout
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn server:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_BOT_TOKEN_SIGNALS
        sync: false
      - key: TELEGRAM_ADMIN_CHAT_ID
        sync: false
      - key: TELEGRAM_ADMIN_CHAT_ID_2
        sync: false
      - key: CRON_SECRET
        sync: false
